version: '3.5'

services:
  agent:
    build:
      context: .
      dockerfile: Dockerfile-compile
    volumes:
      - ../:/work:cached
      - ~/gocache:/gocache
      - ~/gomodcache:/gomodcache
    working_dir: /work
    environment:
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_JOB_ID
      - "BUILDKITE_AGENT_TAGS=queue=default"
      - "BUILDKITE_BUILD_PATH=/buildkite"
      - GOCACHE=/gocache
      - GOMODCACHE=/gomodcache

  ruby:
    image: ruby:2.7.6
    volumes:
      - ..:/work
      - ruby-2-7-6-agent-gem-cache:/usr/local/bundle
    working_dir: /work
    command: /bin/bash
    environment:
      - FULL_AGENT_VERSION
      - AGENT_VERSION
      - BUILD_VERSION

volumes:
  ruby-2-7-6-agent-gem-cache: ~
