version: '2.1'

services:
  agent:
    image: golang:1.10
    working_dir: /go/src/github.com/buildkite/agent
    volumes:
      - ./:/go/src/github.com/buildkite/agent:cached
    environment:
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_JOB_ID
      - "BUILDKITE_AGENT_TAGS=queue=default"
      - "BUILDKITE_BUILD_PATH=/buildkite"
